# Generated by Django 4.0.4 on 2022-05-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
