# Generated by Django 4.0.4 on 2022-05-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookWeb', '0003_book_description_book_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.PositiveSmallIntegerField(choices=[(3, 'D'), (1, 'B'), (0, 'A'), (2, 'C')], default=0)),
                ('bookstand', models.PositiveSmallIntegerField(choices=[(0, 'Front'), (3, 'Right'), (1, 'Back'), (2, 'Left')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='library_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BookWeb.libraryinfo'),
        ),
    ]
