# Generated by Django 4.0.4 on 2022-05-09 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookWeb', '0004_libraryinfo_book_library_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryinfo',
            name='bookstand',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Left'), (1, 'Back'), (3, 'Right'), (0, 'Front')], default=0),
        ),
        migrations.AlterField(
            model_name='libraryinfo',
            name='storage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'B'), (2, 'C'), (0, 'A'), (3, 'D')], default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_review', models.TextField(default='')),
                ('score', models.PositiveSmallIntegerField(default=3)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookWeb.book')),
            ],
        ),
    ]
