# Generated by Django 4.0.4 on 2022-05-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookWeb', '0006_user_remove_book_library_info_delete_libraryinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BookWeb.user'),
            preserve_default=False,
        ),
    ]
